services:
  # 1. FastAPI Backend API
  - type: web
    name: skybook-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: GEMINI_API_KEY
        value: "-AQ.Ab8RN6K1ZAsefD86KqUlM_jpIr1b54ddTY_z3fb_7Wb25fFg7w"

  # 2. React Vite Frontend Static Site
  - type: web
    name: skybook-frontend
    runtime: static
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: skybook-backend
          type: web
          property: host
